"""empty message

Revision ID: 29721bffffaf
Revises: a18eb8676ded
Create Date: 2018-06-22 21:52:48.441592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29721bffffaf'
down_revision = 'a18eb8676ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
