"""empty message

Revision ID: c31441c7d4bb
Revises: 29721bffffaf
Create Date: 2018-06-24 11:33:13.394026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31441c7d4bb'
down_revision = '29721bffffaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('uploader_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'uploader_name')
    # ### end Alembic commands ###
