"""empty message

Revision ID: f11c96fd4a33
Revises: 609f33513ed6
Create Date: 2018-06-30 11:47:33.167004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11c96fd4a33'
down_revision = '609f33513ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approved')
    # ### end Alembic commands ###
